export enum DepositStatus {
  START,

  // FUNDING FLOW
  AWAITING_SIGNER_SETUP,
  AWAITING_BTC_FUNDING_PROOF,

  // FAILED SETUP
  FAILED_SETUP,

  // ACTIVE
  ACTIVE, // includes courtesy call

  // REDEMPTION FLOW
  AWAITING_WITHDRAWAL_SIGNATURE,
  AWAITING_WITHDRAWAL_PROOF,
  REDEEMED,

  // SIGNER LIQUIDATION FLOW
  COURTESY_CALL,
  FRAUD_LIQUIDATION_IN_PROGRESS,
  LIQUIDATION_IN_PROGRESS,
  LIQUIDATED,

  // KEEPER-SPECIFIC (NON-STANDARD STATUS CODES)
  KEEPER_REDEEMING,
  KEEPER_REDEEMED,
}

export enum DepositOperation {
  // redeeming
  REDEEM_TBTC_TO_BTC = 'REDEEM_TBTC_TO_BTC',
  REDEEM_APPROVE_TBTC = 'REDEEM_APPROVE_TBTC', // TODO: approve once?
  REDEEM_PROVIDE_REDEMPTION_SIG = 'REDEEM_PROVIDE_REDEMPTION_SIG',
  REDEEM_PROVIDE_REDEMPTION_PROOF = 'REDEEM_PROVIDE_REDEMPTION_PROOF',
  REDEEM_BTC_RECEPTION = 'REDEEM_BTC_RECEPTION',

  // minting
  MINT_CREATE_DEPOSIT = 'MINT_CREATE_DEPOSIT',
  MINT_RETRIEVE_PUBKEY = 'MINT_RETRIEVE_PUBKEY',
  MINT_FUND_BTC = 'MINT_FUND_BTC',
  MINT_PROVIDE_FUNDING_PROOF = 'MINT_PROVIDE_FUNDING_PROOF',
  MINT_APPROVE_TDT = 'MINT_APPROVE_TDT', // TODO: approve once?
  MINT_TDT_TO_TBTC = 'MINT_TDT_TO_TBTC',
  MINT_TBTC_RECEPTION = 'MINT_TBTC_RECEPTION',
}

export enum DepositOperationStatus {
  START = 'START',
  CONFIRMING = 'CONFIRMING',
  CONFIRMED = 'CONFIRMED',
  ERROR = 'ERROR',
}

export enum PubSubTopic {
  REDEEM_START = 'REDEEM_START',
}
