export enum DepositStatus {
  START,

  // FUNDING FLOW
  AWAITING_SIGNER_SETUP,
  AWAITING_BTC_FUNDING_PROOF,

  // FAILED SETUP
  FAILED_SETUP,

  // ACTIVE
  ACTIVE, // includes courtesy call

  // REDEMPTION FLOW
  AWAITING_WITHDRAWAL_SIGNATURE,
  AWAITING_WITHDRAWAL_PROOF,
  REDEEMED,

  // SIGNER LIQUIDATION FLOW
  COURTESY_CALL,
  FRAUD_LIQUIDATION_IN_PROGRESS,
  LIQUIDATION_IN_PROGRESS,
  LIQUIDATED,

  // KEEPER-SPECIFIC (NON-STANDARD STATUS CODES)
  KEEPER_REDEEMING,
  KEEPER_REDEEMED,
}

export enum DepositRedemptionOperation {
  // redeeming
  TBTC_REDEEM_TBTC_TO_BTC = 'TBTC_REDEEM_TBTC_TO_BTC',
  TBTC_REDEEM_PROVIDE_REDEMPTION_SIG = 'TBTC_REDEEM_PROVIDE_REDEMPTION_SIG',

  // minting
  TBTC_MINT_CREATE_DEPOSIT = 'TBTC_MINT_CREATE_DEPOSIT',
  TBTC_MINT_RETRIEVE_PUBKEY = 'TBTC_MINT_RETRIEVE_PUBKEY',
  TBTC_MINT_PROVIDE_FUNDING_PROOF = 'TBTC_MINT_PROVIDE_FUNDING_PROOF',
  TBTC_MINT_APPROVE_TDT = 'TBTC_MINT_APPROVE_TDT', // TODO: approve once?
  TBTC_MINT_TDT_TO_TBTC = 'TBTC_MINT_TDT_TO_TBTC',

  // for audit and sanity checks - take note of arriving BTC and TBTC
  BTC_RECEPTION = 'BTC_RECEPTION',
  TBTC_RECEPTION = 'TBTC_RECEPTION',
}

export enum DepositRedemptionStatus {
  START = 'START',
  CONFIRMING = 'CONFIRMING',
  CONFIRMED = 'CONFIRMED',
  ERROR = 'ERROR',
}
